package org.zergatstage.model;

import static org.assertj.core.api.Assertions.assertThat;

public class OptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionAllPropertiesEquals(Option expected, Option actual) {
        assertOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionAllUpdatablePropertiesEquals(Option expected, Option actual) {
        assertOptionUpdatableFieldsEquals(expected, actual);
        assertOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionAutoGeneratedPropertiesEquals(Option expected, Option actual) {
        assertThat(actual)
            .as("Verify Option auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionUpdatableFieldsEquals(Option expected, Option actual) {
        assertThat(actual)
            .as("Verify Option relevant properties")
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getCorrect()).as("check correct").isEqualTo(expected.getCorrect()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionUpdatableRelationshipsEquals(Option expected, Option actual) {
        assertThat(actual)
            .as("Verify Option relationships")
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getResponses()).as("check responses").isEqualTo(expected.getResponses()));
    }
}
